server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "custom"
preview_length = 80

[custom_finder]
program = "fuzzel"
args = ["-d"]

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
